#!/bin/bash
wget -qO- https://b.thumbs.redditmedia.com/pE2HOPyyVQJ0m2Aoem9QaRxPa2YowIV79AcEsi2cTek.css | sed -e 's/"#\([a-zA-Z0-9-]\+\)"/\n\$\$\$\1\n/g' | sed '/\$\$\$/!d' | sed -e '/$$$s$/d' | sort -u | sed 's/\$\$\$\([a-zA-Z0-9-]\+\)/\t\tobjTo\.appendChild\(appendFaceThumb\(\"\1\"\)\)\;/g' > anime_prepared
echo "Faces successfully saved..."

#KATE Find and replace Regex to mine faces from css:
#1) FIND:
#	\"\#([a-zA-Z0-9-]+)\"
#	REPLACE WITH:
#	\n$$$\1\n
#2) FIND:
#	^(?!\$\$\$).+
#	DELETE
#3) VIM SORT AND REMOVE DUPLICATES (http://vim.wikia.com/wiki/Sort_lines):
#	:%sort u
#4) FIND:
#	\$\$\$([a-zA-Z0-9-]+)\n
#	REPLACE WITH:
#	objTo\.appendChild\(appendFaceThumb\(\"\1\"\)\)\;\n
