#!/bin/bash
wget -qO- https://b.thumbs.redditmedia.com/e0GAOLlC47rV07iMNWrXGO7ItckdolLZIGO6-YZyCko.css | sed -e 's/"#\([a-zA-Z0-9-]\+\)"/\n\$\$\$\1\n/g' | sed '/\$\$\$/!d' | sort -u | sed 's/\$\$\$\([a-zA-Z0-9-]\+\)/\tobjTo\.appendChild\(appendFaceThumb\(\"\1\"\)\)\;/g' > anime_prepared
echo "Faces successfully saved..."